apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-deployment
  namespace: kubedoom
  labels:
    app: kubedoom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: kubedoom
        image: storaxdev/kubedoom:0.5.0
        ports:
         - protocol: TCP
           containerPort: 5900
      tolerations:
       - key: "CriticalAddonsOnly"
         operator: "Exists"
         effect: "PreferNoSchedule"
