apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:10.13
        ports:
         - protocol: TCP
           containerPort: 5432
        volumeMounts:
          - name: secret
            mountPath: /secret
            readOnly: true
          - name: postgre-pgdata
            mountPath: /var/lib/postgresql/data/pgdata
        env:
          - name: POSTGRES_PASSWORD_FILE
            value: /secret/password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgre-user-pass
                key: username
                optional: false
          - name: POSTGRES_DB
            value: testdatabase
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: secret
          secret:
            secretName: postgre-user-pass
            items:
              - key: password
                path: password
        - name: postgre-pgdata
          persistentVolumeClaim:
            claimName: postgre-pgdata
