apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: default
  labels:
    name: prometheus
spec:
  storageClassName: "csi-ceph-ssd-ms1-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi