apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pgdata
  namespace: postgresql
  labels:
    name: postgresql
spec:
  storageClassName: "csi-ceph-ssd-ms1-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi